desktop: add header comments and usage text to some scripts

diff --git a/.bin/de-config b/.bin/de-config
--- a/.bin/de-config
+++ b/.bin/de-config
@@ -1,9 +1,32 @@
 #!/usr/bin/env bash
+#
+# Get desktop environment configuration.
+#
+# This script is part of my custom desktop environment. It may not work outside
+# of this context.
+#
+# This script requires `toml` and `jq`.
+# It requires $DE_CONFIG to contain the path of a toml file.
+#
+# Author: Stefan Szymanski <stefan.szymanski@posteo.de>
+# Date: 2021-01-20
+# Licence: MIT
 
 if [ ! -r "$DE_CONFIG" ]; then
-    printf "%s\n" "Configuration not found: $$DE_CONFIG is not a readable file."
+    printf "%s\n" "Configuration not found: $$DE_CONFIG is not a readable file." >&2
     exit 1
 fi
+
+usage() {
+    local prog="${0##*/}"
+    cat <<-EOF
+	Usage: $prog get <args>
+
+	Examples:
+	  $prog get pulseaudio.source
+	  $prog get pulseaudio '.sink | to_entries[] | .value.name'
+	EOF
+}
 
 case "$1" in 
     get)
@@ -16,7 +39,11 @@ case "$1" in
             printf "%s\n" "$config"
         fi
         ;;
+    help)
+        usage
+        ;;
     *) 
+        usage >&2
         exit 1
         ;;
 esac
diff --git a/.bin/de-fullscreen b/.bin/de-fullscreen
--- a/.bin/de-fullscreen
+++ b/.bin/de-fullscreen
@@ -1,7 +1,12 @@
 #!/usr/bin/env bash
-
-# Toggle fullscreen for the focused window.
+#
+# Toggle fullscreen mode for a window.
 # 
+# This script is part of my custom desktop environment. It may not work outside
+# of this context.
+#
+# This script requires `pfw`, `jq` and `bspc`.
+#
 # Available fullscreen modes are configured as `fullscreen.<key>`.
 # There must be following properties:
 # - `name` is the display name as shown in the rofi dialog.
@@ -14,13 +19,17 @@
 #   name = "Example"
 #   area = "2560x1440+0+0"
 #   overlaps = ["A", "B"]
+#
+# Author: Stefan Szymanski <stefan.szymanski@posteo.de>
+# Date: 2021-01-20
+# Licence: MIT
 
 STATE_FILE="$HOME/.fullscreen-state"
 TEMP_MONITOR="Fullscreen"
 
 config="$(de-config get "fullscreen")"
 if [ "$?" -gt 0 ]; then
-    printf "%s\n" "Configuration not found"
+    printf "%s\n" "Configuration not found" >&2
     exit 1
 fi
 
@@ -28,11 +37,15 @@ cfg() {
     jq -r "$1" <<< "$config"
 }
 
-_usage() {
-    cat <<-END
-Usage: de-fullscreen toggle [<wid>]
-END
-    exit 1
+usage() {
+    local prog="${0##*/}"
+    cat <<-EOF
+	Usage: $prog toggle [<wid>]
+	
+	Examples:
+	  $prog toggle              # toggle fullscreen for the focused window
+	  $prog toggle 0x01e00005   # toggle fullscreen for the given window
+	EOF
 }
 
 select_mode() {
@@ -127,7 +140,11 @@ case "$1" in
             [ "$pwid" == "$wid" ] && remove_fullscreen "$wid" "$desktop"
         fi
         ;;
+    help)
+        usage
+        ;;
     *)
-        _usage
+        usage >&2
+        exit 1
         ;;
 esac
diff --git a/.bin/de-pulseaudio b/.bin/de-pulseaudio
--- a/.bin/de-pulseaudio
+++ b/.bin/de-pulseaudio
@@ -1,4 +1,33 @@
 #!/usr/bin/env bash
+#
+# Control pulseaudio.
+#
+# This script is part of my custom desktop environment. It may not work outside
+# of this context.
+#
+# This script requires `jq`, `pactl` and `gawk`.
+#
+# Available sources and sinks are configured as `pulseaudio.[sink|source].<key>`.
+# There must be following properties:
+# - `name` is the pulseaudio name of the device.
+# - `title` is the display name of the device.
+#
+# Example toml configuration:
+#
+#   [pulseaudio]
+#       [pulseaudio.sink.speakers]
+#       name = "alsa_output.pci-0000_0a_00.1.hdmi-stereo-extra2"
+#       title = "Speakers"
+#       [pulseaudio.sink.headphones]
+#       name = "alsa_output.pci-0000_0c_00.4.analog-stereo"
+#       title = "Headphones"
+#       [pulseaudio.source.mic]
+#       name = "alsa_input.pci-0000_0c_00.4.analog-stereo"
+#       title = "Mic"
+#
+# Author: Stefan Szymanski <stefan.szymanski@posteo.de>
+# Date: 2021-01-20
+# Licence: MIT
 
 declare -A CMDS
 CMDS=(
@@ -10,36 +39,46 @@ CMDS=(
     [source-set-mute]="set-source-mute"
 )
 
-_usage() {
-    cat <<-END
-Usage: pa -t <command> <args...>
+usage() {
+    local prog="${0##*/}"
+    cat <<-EOF
+	Usage: $prog <command> [<args...>]
 
-Commands:
-    get-sink-names
-    get-sink-name     <sink-key>
-    get-sink-key      <sink-name>
-    get-sink-info     <sink-key>
-    get-sink-volume   <sink-key>
-    get-sink-mute     <sink-key>
-    get-source-names
-    get-source-name   <source-key>
-    get-source-key    <source-name>
-    get-source-info   <source-key>
-    get-source-volume <source-key>
-    get-source-mute   <source-key>
-    set-sink-volume   <sink-key>   <value>
-    set-sink-mute     <sink-key>   <value>
-    set-source-volume <source-key> <value>
-    set-source-mute   <source-key> <value>
+	Commands:
+	  # get sink information
+	  $prog get-sink-names
+	  $prog get-sink-name     <sink-key>
+	  $prog get-sink-key      <sink-name>
+	  $prog get-sink-info     <sink-key>
+	  $prog get-sink-volume   <sink-key>
+	  $prog get-sink-mute     <sink-key>
 
-Argument <value> is the same as for \`pactl set-{sink|souce}-{volume|mute}\`.
-END
-    exit 1
+	  # get source information
+	  $prog get-source-names
+	  $prog get-source-name   <source-key>
+	  $prog get-source-key    <source-name>
+	  $prog get-source-info   <source-key>
+	  $prog get-source-volume <source-key>
+	  $prog get-source-mute   <source-key>
+
+	  # set sink volume or mute state
+	  $prog set-sink-volume   <sink-key>   <value>
+	  $prog set-sink-mute     <sink-key>   <value>
+
+	  # set source volume or mute state
+	  $prog set-source-volume <source-key> <value>
+	  $prog set-source-mute   <source-key> <value>
+
+	  # generate input for desktop panel
+	  $prog panel
+
+	Argument <value> is the same as for \`pactl set-{sink|souce}-{volume|mute}\`.
+	EOF
 }
 
 config="$(de-config get "pulseaudio")"
 if [ "$?" -gt 0 ]; then
-    printf "%s\n" "Configuration not found"
+    printf "%s\n" "Configuration not found" >&2
     exit 1
 fi
 
@@ -171,7 +210,11 @@ case "$1" in
             printf "%s " "$(get_volume_and_mute source "$key")"
         done <<< "$(cfg '.source | to_entries[] | .value.name')"
         ;;
+    help)
+        usage
+        ;;
     *)
-        _usage
+        usage >&2
+        exit 1
         ;;
 esac
diff --git a/.bin/de-temp b/.bin/de-temp
--- a/.bin/de-temp
+++ b/.bin/de-temp
@@ -1,12 +1,48 @@
 #!/usr/bin/env bash
+#
+# Print hardware temperature.
+#
+# This script is part of my custom desktop environment. It may not work outside
+# of this context.
+#
+# This script requires `jq`.
+#
+# Devices are configured as `temp.<key>`.
+# There must be following properties:
+# - `path` is the path to the sysfs file that contains the temperature.
+# - `warn` is the warning temperature threshold.
+# - `crit` is the critical temperature threshold. 
+#
+# Example toml configuration:
+#
+#   [temp]
+#       [temp.cpu]
+#       path = "/sys/class/hwmon/hwmon2/temp2_input"
+#       warn = 65000
+#       crit = 80000
+#
+# Author: Stefan Szymanski <stefan.szymanski@posteo.de>
+# Date: 2021-01-20
+# Licence: MIT
 
 # Print temperatures of configured devices.
 
 config="$(de-config get "temp")"
 if [ "$?" -gt 0 ]; then
-    printf "%s\n" "Configuration not found"
+    printf "%s\n" "Configuration not found" >&2
     exit 1
 fi
+
+usage() {
+    local prog="${0##*/}"
+    cat <<-EOF
+	Usage: $prog [panel]
+
+	Examples:
+	  $prog         # display temperatures
+	  $prog panel   # generate input for desktop panel
+	EOF
+}
 
 cfg() {
     jq -r "$1" <<< "$config"
@@ -19,6 +55,11 @@ celcius() {
 }
 
 case "$1" in
+    '')
+        while read -r label; do
+            printf "%s\n" "$label $(celcius < "$(cfg ".${label}.path")")" 
+        done <<< "$(cfg 'keys_unsorted | to_entries[] | .value')"
+        ;;
     panel)
         # generate output for my lemonbar panel
         while read -r label; do
@@ -34,9 +75,7 @@ case "$1" in
             printf "%s\n" "$(celcius <<< "$temp") $state" 
         done <<< "$(cfg 'keys_unsorted | to_entries[] | .value')" | tr '\n' $' '
         ;;
-    *)
-        while read -r label; do
-            printf "%s\n" "$label $(celcius < "$(cfg ".${label}.path")")" 
-        done <<< "$(cfg 'keys_unsorted | to_entries[] | .value')"
+    help)
+        usage
         ;;
 esac
